wandb_version: 1

D_damp:
  desc: null
  value: 3.6246957980084002
_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1661422442
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 3
      - 16
      4: 3.7.13
      5: 0.12.17
      8:
      - 5
c:
  desc: null
  value: 0.3921079089634244
mu:
  desc: null
  value: 7.237900651934724
sigma:
  desc: null
  value: 0.2770801920353425
