wandb_version: 1

D_damp:
  desc: null
  value: 3.8501261595032528
_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1661424293
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 3
      - 16
      4: 3.7.13
      5: 0.12.17
      8:
      - 5
c:
  desc: null
  value: 0.24349770678560828
mu:
  desc: null
  value: 1.548325516985611
sigma:
  desc: null
  value: 0.7019267071226447
