wandb_version: 1

D_damp:
  desc: null
  value: 12.078650345774523
_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1661423962
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 3
      - 16
      4: 3.7.13
      5: 0.12.17
      8:
      - 5
c:
  desc: null
  value: 0.7880820905436925
mu:
  desc: null
  value: 1.9185112999430913
sigma:
  desc: null
  value: 0.48925405212575623
