wandb_version: 1

Activation:
  desc: null
  value: Tanh
Batch Size:
  desc: null
  value: 100
Case:
  desc: null
  value: ConvDiff 1D
Epochs:
  desc: null
  value: 500
Learning Rate:
  desc: null
  value: 0.005
Model:
  desc: null
  value: U-Net
Normalisation Strategy:
  desc: null
  value: None
Optimizer:
  desc: null
  value: Adam
Scheduler Gamma:
  desc: null
  value: 0.5
Scheduler Step:
  desc: null
  value: 100
Step:
  desc: null
  value: 10
T_in:
  desc: null
  value: 20
T_out:
  desc: null
  value: 60
Test Size:
  desc: null
  value: 100
Train Size:
  desc: null
  value: 900
_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1661433772
    t:
      1:
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 3
      - 16
      4: 3.7.13
      5: 0.12.17
      8:
      - 5
