wandb_version: 1

D_damp:
  desc: null
  value: 5.357487481969402
_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1661422879
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 3
      - 16
      4: 3.7.13
      5: 0.12.17
      8:
      - 5
c:
  desc: null
  value: 0.1265536122862911
mu:
  desc: null
  value: 2.7921704890331567
sigma:
  desc: null
  value: 0.5858129539251473
