wandb_version: 1

D_damp:
  desc: null
  value: 3.9438702478213727
_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1661425449
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 3
      - 16
      4: 3.7.13
      5: 0.12.17
      8:
      - 5
c:
  desc: null
  value: 0.8550657627677849
mu:
  desc: null
  value: 5.987999938063421
sigma:
  desc: null
  value: 0.5515407967572385
