wandb_version: 1

D_damp:
  desc: null
  value: 8.4278987473246
_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1661423102
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 3
      - 16
      4: 3.7.13
      5: 0.12.17
      8:
      - 5
c:
  desc: null
  value: 0.45605905395315516
mu:
  desc: null
  value: 7.864305117313993
sigma:
  desc: null
  value: 0.6967207014277822
